### ISSUE TITLE
Ошибка "movie authorisation string is empty", что делать?

### ISSUE THREAD

**Issue by standone** [REDNBLACK/J-Kinopoisk2IMDB#14]
<img width="640" alt="2016-10-03 09 41 23 am" src="https://cloud.githubusercontent.com/assets/1965119/19029310/c8bbb0ac-894d-11e6-9d58-b0b7c6cb3e3a.png">
Выдаёт такую ошибку, @REDNBLACK, подскажите, пожалуйста, что делать? Фильмы в список imdb импортировались, а вот оценки нет (в файле кинопоиска оценки проставлены). MacOS Sierra 10.12 (16A323)

**Comment by REDNBLACK** [comment]
Скорее всего вы забыли указать "Строка авторизации IMDB" [(скриншот)](https://cloud.githubusercontent.com/assets/1498939/14435615/74ab56f8-0021-11e6-9645-6d44a53ff63e.png), которую нужно получить этим способом - [ссылка](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/blob/master/docs/ObtainIMDBAuthString.pdf)

Укажите ее, и заново запустите в режиме выставления оценок, на тот же файл .xls
Если уверены, что указывали ее, пришлите **config.json** из папки **Пользователи/Имя пользователя/K2IDB** и **K2IDB.log** из папки **Пользователи/Имя пользователя/K2IDB/logs**

**Comment by jurazaika** [comment]
У меня та же история. java.io.IOException: Movie authorisation string is empty!
![default](https://user-images.githubusercontent.com/29569835/27328743-dc44ba02-55bb-11e7-9677-01af7662d431.png)



Куда можно выслать логи, и config.json?

**Comment by REDNBLACK** [comment]
Повторю https://github.com/REDNBLACK/J-Kinopoisk2IMDB/issues/14#issuecomment-251181481

**Comment by jurazaika** [comment]
Вставлял, вот кусок лога
2017-06-20 13:16:18,382 DEBUG logging [LoggerProviders.java:158] Logging Provider: org.jboss.logging.Slf4jLoggerProvider
2017-06-20 13:16:23,461 INFO  MovieHandler [ConnectionCheckHandler.java:41] IMDB url is successfully reached!
2017-06-20 13:16:23,462 INFO  MovieHandler [ParseIDHandler.java:35] Preparing movie Movie(title=Butterfly on a Wheel, year=2006, type=MOVIE, rating=6, imdbId=tt0489664)
2017-06-20 13:16:23,462 INFO  MovieHandler [ParseIDHandler.java:38] Movie is already prepared Movie(title=Butterfly on a Wheel, year=2006, type=MOVIE, rating=6, imdbId=tt0489664)
2017-06-20 13:16:23,462 INFO  MovieHandler [SetRatingHandler.java:33] Setting rating of movie: Movie(title=Butterfly on a Wheel, year=2006, type=MOVIE, rating=6, imdbId=tt0489664)
2017-06-20 13:16:23,494 DEBUG ExchangeObject [ExchangeObject.java:58] Sending request, to url: http://www.imdb.com/title/tt0489664, with headers: {Accept-Encoding=gzip, User-Agent=Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2227.0 Safari/537.36}
2017-06-20 13:16:25,048 DEBUG ExchangeObject [ExchangeObject.java:62] Got response, status code: 200, headers: {Transfer-Encoding=chunked, X-Frame-Options=SAMEORIGIN, Cache-Control=private, Server=HTTPDaemon, Content-Encoding=gzip, Vary=Accept-Encoding,User-Agent, P3P=policyref="http://i.imdb.com/images/p3p.xml",CP="CAO DSP LAW CUR ADM IVAo IVDo CONo OTPo OUR DELi PUBi OTRi BUS PHY ONL UNI PUR FIN COM NAV INT DEM CNT STA HEA PRE LOC GOV OTC ", Date=Tue, 20 Jun 2017 10:16:14 GMT, Content-Type=text/html; charset=iso-8859-1}
2017-06-20 13:16:25,263 INFO  MovieHandler [SetRatingHandler.java:70] Error setting rating of movie: {}
java.io.IOException: Movie authorisation string is empty!
	at org.f0w.k2i.core.handler.SetRatingHandler.handleMovie(SetRatingHandler.java:55)
	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:72)
	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
	at org.f0w.k2i.core.handler.MovieHandler.handle(MovieHandler.java:76)
	at org.f0w.k2i.core.Client.run(Client.java:77)
	at java.util.concurrent.Executors$RunnableAdapter.call(Unknown Source)
	at java.util.concurrent.FutureTask.run(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)

**Comment by REDNBLACK** [comment]
Выслать можно мне на почту - rednblack@protonmail.com
Попробуйте снова получить строку авторизации, выйдите и зайдите вновь на imdb. 
Похоже что сессия прервалась.

**Comment by jurazaika** [comment]
Я уже пробовал несколько раз. перевходил на imdb, вытирал каталог  K2IDB, не помогало ( В любом случае спасибо за продукт и помощь! Сейчас отправлю
