### ISSUE TITLE
jar не запускается

### ISSUE THREAD

**Issue by extempl** [REDNBLACK/J-Kinopoisk2IMDB#26]
```
$ java -jar ./Kinopoisk2IMDB_1.2.jar
Exception in Application start method
Exception in thread "JavaFX Application Thread" java.lang.ExceptionInInitializerError
	at javafx.scene.control.ProgressBar.createDefaultSkin(ProgressBar.java:97)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Node.processCSS(Node.java:9051)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.access$3600(Scene.java:159)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2392)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Caused by: java.lang.NullPointerException
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409)
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413)
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73)
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138)
	at javafx.scene.text.Text.getTextLayout(Text.java:229)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$2.invalidated(Text.java:389)
	at javafx.beans.property.StringPropertyBase.markInvalid(StringPropertyBase.java:109)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:144)
	at javafx.beans.property.StringPropertyBase.set(StringPropertyBase.java:49)
	at javafx.scene.text.Text.setText(Text.java:370)
	at javafx.scene.text.Text.<init>(Text.java:129)
	at com.sun.javafx.scene.control.skin.ProgressIndicatorSkin.<clinit>(ProgressIndicatorSkin.java:166)
	... 18 more
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at com.sun.javafx.scene.control.skin.AccordionSkin.layoutChildren(AccordionSkin.java:171)
	at javafx.scene.control.Control.layoutChildren(Control.java:578)
	at javafx.scene.Parent.layout(Parent.java:1087)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Parent.layout(Parent.java:1093)
	at javafx.scene.Scene.doLayoutPass(Scene.java:552)
	at javafx.scene.Scene$ScenePulseListener.pulse(Scene.java:2397)
	at com.sun.javafx.tk.Toolkit.lambda$runPulse$30(Toolkit.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.Toolkit.runPulse(Toolkit.java:354)
	at com.sun.javafx.tk.Toolkit.firePulse(Toolkit.java:381)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:510)
	at com.sun.javafx.tk.quantum.QuantumToolkit.pulse(QuantumToolkit.java:490)
	at com.sun.javafx.tk.quantum.QuantumToolkit.lambda$runToolkit$404(QuantumToolkit.java:319)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.lang.reflect.InvocationTargetException
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.sun.javafx.application.LauncherImpl.launchApplicationWithArgs(LauncherImpl.java:389)
	at com.sun.javafx.application.LauncherImpl.launchApplication(LauncherImpl.java:328)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at sun.launcher.LauncherHelper$FXHelper.main(LauncherHelper.java:767)
Caused by: java.lang.RuntimeException: Exception in Application start method
	at com.sun.javafx.application.LauncherImpl.launchApplication1(LauncherImpl.java:917)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication$155(LauncherImpl.java:182)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NullPointerException
	at com.sun.javafx.font.MacFontFinder.populateFontFileNameMap(MacFontFinder.java:99)
	at com.sun.javafx.font.PrismFontFactory.getFullNameToFileMap(PrismFontFactory.java:1740)
	at com.sun.javafx.font.PrismFontFactory.getFontResource(PrismFontFactory.java:469)
	at com.sun.javafx.font.LogicalFont.getSlot0Resource(LogicalFont.java:194)
	at com.sun.javafx.font.LogicalFont.getDefaultAAMode(LogicalFont.java:409)
	at com.sun.javafx.font.LogicalFont.getStrike(LogicalFont.java:413)
	at com.sun.javafx.font.PrismFont.getStrike(PrismFont.java:73)
	at com.sun.javafx.text.PrismTextLayout.setContent(PrismTextLayout.java:138)
	at javafx.scene.text.Text.getTextLayout(Text.java:229)
	at javafx.scene.text.Text.needsFullTextLayout(Text.java:184)
	at javafx.scene.text.Text.access$200(Text.java:95)
	at javafx.scene.text.Text$5.invalidated(Text.java:501)
	at javafx.beans.property.ObjectPropertyBase.markInvalid(ObjectPropertyBase.java:111)
	at javafx.beans.property.ObjectPropertyBase.bind(ObjectPropertyBase.java:174)
	at javafx.css.StyleableObjectProperty.bind(StyleableObjectProperty.java:75)
	at com.sun.javafx.scene.control.skin.LabeledText.<init>(LabeledText.java:82)
	at com.sun.javafx.scene.control.skin.LabeledSkinBase.<init>(LabeledSkinBase.java:125)
	at com.sun.javafx.scene.control.skin.TitledPaneSkin.<init>(TitledPaneSkin.java:76)
	at javafx.scene.control.TitledPane.createDefaultSkin(TitledPane.java:276)
	at javafx.scene.control.Control.impl_processCSS(Control.java:872)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.control.Control.impl_processCSS(Control.java:875)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Parent.impl_processCSS(Parent.java:1280)
	at javafx.scene.Node.processCSS(Node.java:9058)
	at javafx.scene.Scene.doCSSPass(Scene.java:545)
	at javafx.scene.Scene.preferredSize(Scene.java:1643)
	at javafx.scene.Scene.impl_preferredSize(Scene.java:1720)
	at javafx.stage.Window$9.invalidated(Window.java:846)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:109)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at javafx.stage.Window.setShowing(Window.java:922)
	at javafx.stage.Window.show(Window.java:937)
	at javafx.stage.Stage.show(Stage.java:259)
	at org.f0w.k2i.gui.Main.start(Main.java:40)
	at com.sun.javafx.application.LauncherImpl.lambda$launchApplication1$162(LauncherImpl.java:863)
	at com.sun.javafx.application.PlatformImpl.lambda$runAndWait$175(PlatformImpl.java:326)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception running application org.f0w.k2i.gui.Main
```

```
macOS Mojave 10.14.2 (18C54)

java version "1.8.0_121"
Java(TM) SE Runtime Environment (build 1.8.0_121-b13)
Java HotSpot(TM) 64-Bit Server VM (build 25.121-b13, mixed mode)
```

**Comment by extempl** [comment]
Конкретно эта ошибка решается сбросом библиотеки шрифтов. Все удалённые шрифты будут сохранены в `Fonts (Removed)`. Ошибка исправлена в JDK10, но возможности апгрейда JRE пока нет.
