### ISSUE TITLE
Java 11+: NoClassDefFoundError exception in net.sf.launch4j.Main.main(Main.java:58)

### ISSUE THREAD

**Issue by whoizit** [REDNBLACK/J-Kinopoisk2IMDB#34]
```
$ java -jar Kinopoisk2IMDB-1.2.6.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver
	at net.sf.launch4j.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.io.HierarchicalStreamDriver
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:583)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:178)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	... 1 more
```

**Comment by whoizit** [comment]
```
$ java --version
java 12.0.1 2019-04-16
Java(TM) SE Runtime Environment (build 12.0.1+12)
Java HotSpot(TM) 64-Bit Server VM (build 12.0.1+12, mixed mode, sharing)
```

**Comment by extempl** [comment]
Попробуйте предпоследнюю стабильную версию, на 12 я ещё не тестировал. 
Валится прямо на запуске? Или при каком-то действии?

**Comment by whoizit** [comment]
на 11 ровно тоже самое. Прямо при запуске

**Comment by extempl** [comment]
Это всё JDK, последняя JRE которая отдельно от JDK - 8 версии

**Comment by whoizit** [comment]
```
9 aur/jre 12.0.1-1 (+598 3.02%) (Installed)
    Oracle Java Runtime Environment
8 extra/jre8-openjdk-headless 8.u212-1 (25.9 MiB 95.2 MiB) (Installed)
    OpenJDK Java 8 headless runtime environment
7 extra/jre8-openjdk 8.u212-1 (163.8 KiB 412.0 KiB) (Installed)
    OpenJDK Java 8 full runtime environment
6 extra/jre7-openjdk-headless 7.u171_2.6.13-1 (42.6 MiB 78.3 MiB) 
    OpenJDK Java 7 headless runtime environment
5 extra/jre7-openjdk 7.u171_2.6.13-1 (160.4 KiB 444.0 KiB) 
    OpenJDK Java 7 full runtime environment
4 extra/jre10-openjdk-headless 10.0.2.u13-1 (34.1 MiB 169.6 MiB) (Installed)
    OpenJDK Java 10 headless runtime environment
3 extra/jre10-openjdk 10.0.2.u13-1 (230.1 KiB 655.0 KiB) (Installed)
    OpenJDK Java 10 full runtime environment
2 extra/jre-openjdk-headless 11.0.3.u4-1 (31.8 MiB 156.6 MiB) (Installed)
    OpenJDK Java 11 headless runtime environment
1 extra/jre-openjdk 11.0.3.u4-1 (176.5 KiB 532.0 KiB) (Installed)
    OpenJDK Java 11 full runtime environment

```

я попробовал 1, 3, 7, 9. Всё тоже самое, только вывод между 1.2.6 и 1.2.5 разный

```
$ java -jar Kinopoisk2IMDB-1.2.6.jar 
Exception in thread "main" java.lang.NoClassDefFoundError: com/thoughtworks/xstream/io/HierarchicalStreamDriver
	at net.sf.launch4j.Main.main(Main.java:58)
Caused by: java.lang.ClassNotFoundException: com.thoughtworks.xstream.io.HierarchicalStreamDriver
	at java.net.URLClassLoader.findClass(URLClassLoader.java:382)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:349)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 1 more
$ java -jar Kinopoisk2IMDB-1.2.5.jar 
Error: Could not find or load main class org.f0w.k2i.gui.Main
$ java -showversion
openjdk version "1.8.0_212"
OpenJDK Runtime Environment (build 1.8.0_212-b01)
OpenJDK 64-Bit Server VM (build 25.212-b01, mixed mode)
```

**Comment by whoizit** [comment]
```
$ archlinux-java status
Available Java environments:
  java-10-openjdk
  java-11-openjdk
  java-12-jdk
  java-8-openjdk/jre (default)
```

**Comment by extempl** [comment]
Посмотрите этот issue: https://github.com/REDNBLACK/J-Kinopoisk2IMDB/issues/21, Может быть Ваш случай

> проблема в том, что в поставке openjdk нет JavaFX. Решается либо установкой обычной Java от Oracle, либо как подсказали тут [#21 (comment)](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/issues/21#issuecomment-350875543)

**Comment by whoizit** [comment]
1.2.5 запустилась при установке:
extra/java-openjfx 8.u172-2 (25.4 MiB 77.9 MiB) 
    Java OpenJFX 8 client application platform (open-source implementation of JavaFX)

**Comment by extempl** [comment]
Тогда точно JavaFX зависимость, проверьте пожалуйста на 12 версии. Или это на 12 уже?

**Comment by whoizit** [comment]
это версия JavaFX 8 (`java-openjfx 8.u172-2`) для 8 jre. Для других версий JavaFX я что-то не наблюдаю.

На этом не работает:
```
aur/jre 12.0.1-1 (+598 3.02%) (Installed)
    Oracle Java Runtime Environment
```

**Comment by extempl** [comment]
Видимо нет пока поддержки для JDK, тут остаётся только ждать.
