### ISSUE TITLE
Добавить Kinorium 2 IMDB importer

### ISSUE THREAD

**Issue by bystritskiy** [REDNBLACK/J-Kinopoisk2IMDB#46]
Так как [Кинопоиск убрали функцию выгрузки в excel своих оценок](https://kinopoisk.userecho.com/communities/4/topics/1331-eksport-v-excel-libo-funktsiya-bekapa), то можно использовать такую схему:

1. kinorium может подгрузить все оценки из kinopoisk
2. в kinorium делаем экспорт csv
3. и уже эту csv подставляем в J-Kinopoisk2IMDB

**Comment by grcool** [comment]
Пишет "Были обработаны все 0 фильмов, без ошибок". 
В логах пишется:
```
2020-05-20 14:58:38,784 ERROR h2database [TraceWriterAdapter.java:69] K2IDB:jdbc[5] java.lang.Exception: Open Stack Trace
	at org.h2.util.CloseWatcher.register(CloseWatcher.java:100)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:138)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:38)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:58)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections.addConnections(PooledConnections.java:106)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections.<init>(PooledConnections.java:40)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections.<init>(PooledConnections.java:19)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections$Builder.build(PooledConnections.java:138)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:110)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:74)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:876)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at com.google.inject.persist.jpa.JpaPersistService.start(JpaPersistService.java:107)
	at org.f0w.k2i.core.Client.<init>(Client.java:73)
	at org.f0w.k2i.gui.ClientExecutor.init(ClientExecutor.java:52)
	at org.f0w.k2i.gui.ClientExecutor.run(ClientExecutor.java:56)
	at org.f0w.k2i.gui.Controller.handleStartAction(Controller.java:325)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
	at java.lang.Thread.run(Unknown Source)

org.h2.message.DbException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.get(DbException.java:179)
	at org.h2.message.DbException.get(DbException.java:155)
	at org.h2.message.DbException.get(DbException.java:144)
	at org.h2.jdbc.JdbcConnection.closeOld(JdbcConnection.java:197)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:137)
	at org.h2.jdbc.JdbcConnection.<init>(JdbcConnection.java:103)
	at org.h2.Driver.connect(Driver.java:69)
	at org.hibernate.engine.jdbc.connections.internal.DriverConnectionCreator.makeConnection(DriverConnectionCreator.java:38)
	at org.hibernate.engine.jdbc.connections.internal.BasicConnectionCreator.createConnection(BasicConnectionCreator.java:58)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections.addConnections(PooledConnections.java:106)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections.<init>(PooledConnections.java:40)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections.<init>(PooledConnections.java:19)
	at org.hibernate.engine.jdbc.connections.internal.PooledConnections$Builder.build(PooledConnections.java:138)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.buildPool(DriverManagerConnectionProviderImpl.java:110)
	at org.hibernate.engine.jdbc.connections.internal.DriverManagerConnectionProviderImpl.configure(DriverManagerConnectionProviderImpl.java:74)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.buildJdbcConnectionAccess(JdbcEnvironmentInitiator.java:145)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:66)
	at org.hibernate.engine.jdbc.env.internal.JdbcEnvironmentInitiator.initiateService(JdbcEnvironmentInitiator.java:35)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:88)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:234)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:208)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.engine.jdbc.internal.JdbcServicesImpl.configure(JdbcServicesImpl.java:51)
	at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.configureService(StandardServiceRegistryImpl.java:94)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.initializeService(AbstractServiceRegistryImpl.java:217)
	at org.hibernate.service.internal.AbstractServiceRegistryImpl.getService(AbstractServiceRegistryImpl.java:189)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.handleTypes(MetadataBuildingProcess.java:352)
	at org.hibernate.boot.model.process.spi.MetadataBuildingProcess.complete(MetadataBuildingProcess.java:111)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.metadata(EntityManagerFactoryBuilderImpl.java:848)
	at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl.build(EntityManagerFactoryBuilderImpl.java:876)
	at org.hibernate.jpa.HibernatePersistenceProvider.createEntityManagerFactory(HibernatePersistenceProvider.java:58)
	at javax.persistence.Persistence.createEntityManagerFactory(Persistence.java:55)
	at com.google.inject.persist.jpa.JpaPersistService.start(JpaPersistService.java:107)
	at org.f0w.k2i.core.Client.<init>(Client.java:73)
	at org.f0w.k2i.gui.ClientExecutor.init(ClientExecutor.java:52)
	at org.f0w.k2i.gui.ClientExecutor.run(ClientExecutor.java:56)
	at org.f0w.k2i.gui.Controller.handleStartAction(Controller.java:325)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:86)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:49)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Node.fireEvent(Node.java:8411)
	at javafx.scene.control.Button.fire(Button.java:185)
	at com.sun.javafx.scene.control.behavior.ButtonBehavior.mouseReleased(ButtonBehavior.java:182)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:96)
	at com.sun.javafx.scene.control.skin.BehaviorSkinBase$1.handle(BehaviorSkinBase.java:89)
	at com.sun.javafx.event.CompositeEventHandler$NormalEventHandlerRecord.handleBubblingEvent(CompositeEventHandler.java:218)
	at com.sun.javafx.event.CompositeEventHandler.dispatchBubblingEvent(CompositeEventHandler.java:80)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:238)
	at com.sun.javafx.event.EventHandlerManager.dispatchBubblingEvent(EventHandlerManager.java:191)
	at com.sun.javafx.event.CompositeEventDispatcher.dispatchBubblingEvent(CompositeEventDispatcher.java:59)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:58)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.BasicEventDispatcher.dispatchEvent(BasicEventDispatcher.java:56)
	at com.sun.javafx.event.EventDispatchChainImpl.dispatchEvent(EventDispatchChainImpl.java:114)
	at com.sun.javafx.event.EventUtil.fireEventImpl(EventUtil.java:74)
	at com.sun.javafx.event.EventUtil.fireEvent(EventUtil.java:54)
	at javafx.event.Event.fireEvent(Event.java:198)
	at javafx.scene.Scene$MouseHandler.process(Scene.java:3757)
	at javafx.scene.Scene$MouseHandler.access$1500(Scene.java:3485)
	at javafx.scene.Scene.impl_processMouseEvent(Scene.java:1762)
	at javafx.scene.Scene$ScenePeerListener.mouseEvent(Scene.java:2494)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:394)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler$MouseEventNotification.run(GlassViewEventHandler.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.lambda$handleMouseEvent$2(GlassViewEventHandler.java:432)
	at com.sun.javafx.tk.quantum.QuantumToolkit.runWithoutRenderLock(QuantumToolkit.java:410)
	at com.sun.javafx.tk.quantum.GlassViewEventHandler.handleMouseEvent(GlassViewEventHandler.java:431)
	at com.sun.glass.ui.View.handleMouseEvent(View.java:555)
	at com.sun.glass.ui.View.notifyMouse(View.java:937)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$4(WinApplication.java:186)
	at java.lang.Thread.run(Unknown Source)
Caused by: org.h2.jdbc.JdbcSQLException: Незакрытое приложением соединение уничтожено сборщиком мусора
The connection was not closed by the application and is garbage collected [90018-197]
	at org.h2.message.DbException.getJdbcSQLException(DbException.java:357)
	... 87 common frames omitted
```

**Comment by ward276** [comment]
если цель НЕ допилить именно этот проект, а сделать импорт оценок, то используя kinorium и этот скрипт: https://greasyfork.org/en/scripts/23584-imdb-list-importer/feedback можно заимпортить фильмы с оценками.

Единственное что там не хватает это IDшника IMDB (или прямой урлы на фильм. IDшник выглядит как tt2342323) - если вам это поможет )

сделал бы сам и выложил сюда, но у меня лапки )

**Comment by slava-nat** [comment]
> если цель НЕ допилить именно этот проект, а сделать импорт оценок, то используя kinorium и этот скрипт: https://greasyfork.org/en/scripts/23584-imdb-list-importer/feedback можно заимпортить фильмы с оценками.
> 
> Единственное что там не хватает это IDшника IMDB (или прямой урлы на фильм. IDшник выглядит как tt2342323) - если вам это поможет )
> 
> сделал бы сам и выложил сюда, но у меня лапки )

Указанный скрипт умеет импортировать только список фильмов (без рейтингов).

Может, имеет смысл подкорректировать поля экспорта из Кинориума, чтобы они выглядели, как от Кинопоиска, и тогда скормить уже изменённый файл данной программе.

**Comment by slava-nat** [comment]
На данный момент для переноса списка просмотренных фильмов и оценок из Кинопоиска в IMDB через Кинориум можно пользоваться следующей схемой (хотя придётся немного помучаться):

Идея заключается в том, чтобы получить файл с данными из Кинопоиска и изменить его так, чтобы его смогла "съесть" данная программа.

1. Регистрируемся на Кинориуме и в настройках аккаунта импортируем данные из Кинопоиска;
2. Там же в настройках запрашиваем экспорт, который пришлют на почту в формате `.csv`;
3. Далее нам нужно изменить формат полученного файла (замаскировать под экспорт из Кинопоиска), чтобы в конце его можно было скормить текущей программе. Для этого находим в архиве данной программы пример экспорта из Кинопоиска. Например, вот здесь:
[J-Kinopoisk2IMDB/tree/master/core/src/test/resources/parser](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/tree/master/core/src/test/resources/parser)
есть файл `test_data_file_exported_from_lists.xls.` Скачиваем его. Несмотря на то что расширение файла `.xls` записан он в формате HTML;
4. Затем скачанный файл открываем Экселем или LibreOffice Calc и подставляем свои данные из экспорта из Кинориума (просто копируя столбцы). Самые важные поля: `русскоязычное название`, `оригинальное название`, `год` и `моя оценка`. Остальные поля можно оставить пустыми;
5. Дальше нажимаем Сохранить Как и ВАЖНО выбираем формат HTML;
6. Затем открываем этот файл и тестовый файл Кинопоиска любым текстовым редактором и замечаем, что шапки отличаются. Копируем шапку (всё до первой строки с фильмами) из тестового файла и вставляем её в файл с нашими фильмами. Сохраняем. Изменяем расширение на `.xls`.
7. Всё. Теперь наш файл спокойно съест данная программа. Следуем дальше инструкциям программы для импорта фильмов и оценок.

**Comment by grcool** [comment]
slava-nat, спасибо за инструкцию) После манипуляций с файлом программа приняла файл, нашла около половины фильмов из списка и якобы выставила оценки) На IMDB оценки так и не появились))
```
2020-05-25 22:53:55,370 INFO  MovieHandler [ParseIDHandler.java:59] Movie IMDB id successfully found: tt5640196
2020-05-25 22:53:55,370 INFO  MovieHandler [SetRatingHandler.java:29] Setting rating of movie: Movie(title=Stardust, year=2007, type=MOVIE, rating=10, imdbId=tt5640196)
2020-05-25 22:53:55,370 INFO  MovieHandler [SetRatingHandler.java:55] Movie rating was successfully set
2020-05-25 22:53:55,376 INFO  MovieHandler [SaveChangesHandler.java:28] Changes were successfully saved to storage
2020-05-25 22:53:55,403 INFO  MovieHandler [ConnectionCheckHandler.java:39] IMDB URL is successfully reached!
```

**Comment by slava-nat** [comment]
> slava-nat, спасибо за инструкцию) После манипуляций с файлом программа приняла файл, нашла около половины фильмов из списка и якобы выставила оценки) На IMDB оценки так и не появились))

Пожалуйста)
Рейтинги программа автоматически не добавляет. Она создаёт файл `ratings.json`, который нужно самому запустить на сайте imdb, как это показано на вот этом [видео](https://dsh.re/9322e) (+ читай [инструкцию](https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%B8%D0%BC%D0%BF%D0%BE%D1%80%D1%82-%D1%80%D0%B5%D0%B9%D1%82%D0%B8%D0%BD%D0%B3%D0%B0)). Работает не быстро, но добавляет все рейтинги.

P.S. У меня тоже программа распознала лишь половину фильмом. Посмотрим, может, я напишу свою, которая сможет на просторах интернета искать айди фильма на IMDB (они выглядят так: tt6966692). Тогда можно было бы подставить всё в скрипт, указанный [здесь](https://github.com/REDNBLACK/J-Kinopoisk2IMDB/issues/46#issuecomment-632229874).

**Comment by grcool** [comment]
Кажется гораздо проще проставить все вручную)))
![image](https://user-images.githubusercontent.com/2117206/82843271-593b9d80-9ee5-11ea-8bfd-88836f756127.png)

**Comment by slava-nat** [comment]
> Кажется гораздо проще проставить все вручную)))
> ![image](https://user-images.githubusercontent.com/2117206/82843271-593b9d80-9ee5-11ea-8bfd-88836f756127.png)

Совсем необязательно всё время нажимать на ОК. Скрипт сам всё делает. Через некоторое время это окошко покажет success: 20 и т.д.

**Comment by grcool** [comment]
Не, у меня после этого окна вообще больше ничего не происходит)

**Comment by extempl** [comment]
@grcool Когда скрипт запускаете находитесь в списке в который импортировали фильмы?
Оно берёт total из строки `6 titles`: https://dsh.re/56600
Видимо у вас или другая страница, где нет этого элемента или там всего несколько фильмов. 
Окно результатов должно выводиться только в конце, когда суммарное кол-во результатов  == общему кол-ву фильмов в списке.

**Comment by extempl** [comment]
@grcool, @slava-nat 
На счёт "половины фильмов" - обратите внимание на этот раздел: https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%B4%D0%BE%D0%BF%D0%BE%D0%BB%D0%BD%D0%B8%D1%82%D0%B5%D0%BB%D1%8C%D0%BD%D1%8B%D0%B5
И на этот (описание поля Тип запроса): https://github.com/REDNBLACK/J-Kinopoisk2IMDB#%D0%BF%D0%BE%D0%B4%D1%80%D0%BE%D0%B1%D0%BD%D0%BE%D0%B5-%D0%BE%D0%BF%D0%B8%D1%81%D0%B0%D0%BD%D0%B8%D0%B5-%D0%B4%D0%BE%D1%81%D1%82%D1%83%D0%BF%D0%BD%D1%8B%D1%85-%D0%BE%D0%BF%D1%86%D0%B8%D0%B9

**Comment by grcool** [comment]
Всем спасибо за советы, процесс наконец налажен) Из 850 тайтлов вручную пришлось обработать около 50 - подцепились всякие короткометражки, вырезанные сцены, документалки и making of)

**Comment by tgptgptgp** [comment]
Жесть я даже не понимаю как скачать test_data_file_exported_from_lists.xls

**Comment by extempl** [comment]
> Жесть я даже не понимаю как скачать test_data_file_exported_from_lists.xls

https://raw.githubusercontent.com/REDNBLACK/J-Kinopoisk2IMDB/master/core/src/test/resources/parser/test_data_file_exported_from_lists.xls

**Comment by tgptgptgp** [comment]
Не я просто не понимаю вроде все правильно сделал все равно ошибка auth sting (at main) length is less or equal to 10. А просто экзешник запустить достаточно или еще что надо сделать ?

**Comment by tgptgptgp** [comment]
Может cURL какой-то надо добавлять перед запуском ?

**Comment by tgptgptgp** [comment]
А ну хотя та же самая ошибка когда я тестовый неизмененный файл вставляю
